name: flutter_hangman
description: Hangman Game

version: 1.2.0+4070

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rflutter_alert: ^1.0.3
  material_design_icons_flutter: ^3.2.4495
  path: ^1.6.4
  flutter_spinkit: ^4.1.2
  date_format: ^1.0.8
  vibration: ^1.4.0
  admob_flutter: ^0.3.4
  rate_my_app: ^0.6.1+6
  shared_preferences: ^0.5.7+3
  flutter_animation_set: any
  url_launcher: ^5.4.11
  flame: ^0.22.1
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  connectivity: ^0.4.9
  

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - images/
    - res/
    - images/ProfilePics/
    - images/onboard/
    - assets/
    - assets/audio/
  fonts:
    - family: PatrickHand
      fonts:
        - asset: fonts/PatrickHand-Regular.ttf
    - family: FiraMono
      fonts:
        - asset: fonts/FiraMono-Bold.ttf
        - asset: fonts/FiraMono-Regular.ttf